// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package noise

import (
	"bytes"
	"crypto/ecdh"
	"crypto/rand"
	"encoding/hex"
	"strings"
	"testing"
)

func handshake(t *testing.T, ipsk, rpsk []byte) (ic1, ic2, rc1, rc2 *CipherState, err error) {
	t.Helper()
	ihs, err := NewHandshakeState(true, ipsk)
	if err != nil {
		t.Fatal(err)
	}
	rhs, err := NewHandshakeState(false, rpsk)
	if err != nil {
		t.Fatal(err)
	}
	m1, c1, c2, err := ihs.WriteMessage(nil, []byte("payload one"))
	if err != nil || c1 != nil || c2 != nil {
		t.Fatalf("initiator WriteMessage: %v, %v, %v", err, c1, c2)
	}
	p1, c1, c2, err := rhs.ReadMessage(nil, m1)
	if err != nil {
		return nil, nil, nil, nil, err
	}
	if string(p1) != "payload one" || c1 != nil || c2 != nil {
		t.Fatalf("responder ReadMessage: %q, %v, %v", p1, c1, c2)
	}
	m2, rc1, rc2, err := rhs.WriteMessage(nil, []byte("payload two"))
	if err != nil || rc1 == nil || rc2 == nil {
		t.Fatalf("responder WriteMessage: %v", err)
	}
	p2, ic1, ic2, err := ihs.ReadMessage(nil, m2)
	if err != nil {
		return nil, nil, nil, nil, err
	}
	if string(p2) != "payload two" || ic1 == nil || ic2 == nil {
		t.Fatalf("initiator ReadMessage: %q", p2)
	}
	return ic1, ic2, rc1, rc2, nil
}

func TestHandshakeAndTransport(t *testing.T) {
	psk := make([]byte, 32)
	rand.Read(psk)
	ic1, ic2, rc1, rc2, err := handshake(t, psk, psk)
	if err != nil {
		t.Fatal(err)
	}

	// Initiator sends with c1, responder receives with c1; several messages.
	for i := 0; i < 3; i++ {
		msg := []byte(strings.Repeat("ping", i+1))
		ct, err := ic1.Encrypt(nil, nil, msg)
		if err != nil {
			t.Fatal(err)
		}
		pt, err := rc1.Decrypt(nil, nil, ct)
		if err != nil || !bytes.Equal(pt, msg) {
			t.Fatalf("i->r message %d: %q, %v", i, pt, err)
		}
	}
	// Responder sends with c2.
	ct, err := rc2.Encrypt(nil, nil, []byte("pong"))
	if err != nil {
		t.Fatal(err)
	}
	pt, err := ic2.Decrypt(nil, nil, ct)
	if err != nil || string(pt) != "pong" {
		t.Fatalf("r->i message: %q, %v", pt, err)
	}

	// Tampered ciphertext must fail.
	ct, err = ic1.Encrypt(nil, nil, []byte("x"))
	if err != nil {
		t.Fatal(err)
	}
	ct[0] ^= 1
	if _, err := rc1.Decrypt(nil, nil, ct); err == nil {
		t.Fatal("tampered ciphertext decrypted")
	}
}

func TestWrongPSK(t *testing.T) {
	psk1 := make([]byte, 32)
	psk2 := make([]byte, 32)
	rand.Read(psk1)
	rand.Read(psk2)
	if _, _, _, _, err := handshake(t, psk1, psk2); err == nil {
		t.Fatal("handshake succeeded with mismatched PSKs")
	}
}

func TestBadPSKLength(t *testing.T) {
	if _, err := NewHandshakeState(true, make([]byte, 16)); err == nil {
		t.Fatal("NewHandshakeState accepted 16-byte PSK")
	}
}

func TestFailedHandshakeIsDead(t *testing.T) {
	psk := make([]byte, 32)
	rand.Read(psk)
	ihs, err := NewHandshakeState(true, psk)
	if err != nil {
		t.Fatal(err)
	}
	rhs, err := NewHandshakeState(false, psk)
	if err != nil {
		t.Fatal(err)
	}
	m1, _, _, err := ihs.WriteMessage(nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	// Corrupt the payload so decryptAndHash fails after the responder
	// has already mixed the initiator's ephemeral into its state.
	bad := bytes.Clone(m1)
	bad[len(bad)-1] ^= 1
	if _, _, _, err := rhs.ReadMessage(nil, bad); err == nil {
		t.Fatal("ReadMessage accepted corrupted message")
	}
	// The responder must not accept a retry with the good message.
	if _, _, _, err := rhs.ReadMessage(nil, m1); err == nil {
		t.Fatal("ReadMessage succeeded after an earlier failure")
	}
	if _, _, _, err := rhs.WriteMessage(nil, nil); err == nil {
		t.Fatal("WriteMessage succeeded after an earlier failure")
	}
}

// The Noise_NNpsk0_25519_ChaChaPoly_SHA256 test vector from the
// Cacophony test suite, which is generated by an independent
// implementation of the Noise Protocol Framework:
// https://raw.githubusercontent.com/centromere/cacophony/master/vectors/cacophony.txt
var vector = struct {
	prologue      string
	psk           string
	initEphemeral string
	respEphemeral string
	handshakeHash string
	messages      []struct{ payload, ciphertext string }
}{
	prologue:      "4a6f686e2047616c74",
	psk:           "54686973206973206d7920417573747269616e20706572737065637469766521",
	initEphemeral: "893e28b9dc6ca8d611ab664754b8ceb7bac5117349a4439a6b0569da977c464a",
	respEphemeral: "bbdb4cdbd309f1a1f2e1456967fe288cadd6f712d65dc7b7793d5e63da6b375b",
	handshakeHash: "f4d03dc34495c95729ea6de9e1b59004b59733102488b3e24bc441e0be208eaf",
	messages: []struct{ payload, ciphertext string }{
		{"4c756477696720766f6e204d69736573", "ca35def5ae56cec33dc2036731ab14896bc4c75dbb07a61f879f8e3afa4c794479b962b8aff8485742ac32f905ba45369e2465fb59e138a93d67a0d1266b6a54"},
		{"4d757272617920526f746862617264", "95ebc60d2b1fa672c1f46a8aa265ef51bfe38e7ccb39ec5be34069f144808843d6062704d5a9c422a8e834423f8c1feada7e8d0d910a1a2cd030fb584221e3"},
		{"462e20412e20486179656b", "e632c3763d7669067383433197a3baddf146e9e70ad4b4e9e59e0f"},
		{"4361726c204d656e676572", "64c6bee32ea91c8474bb4c21d7a700109ad45af77b29764ba5eb1e"},
		{"4a65616e2d426170746973746520536179", "e2fa0bed0603b62d3ccac2ecabbf3fe33f3e86514909b323361626266cb2471cc8"},
		{"457567656e2042f6686d20766f6e2042617765726b", "0c01dc9cec1fe4ddd692e8dd32188aa351088dc91183639a53b57aa4692b5ebdef8b8ca111"},
	},
}

func unhex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func ephemeral(t *testing.T, s string) *ecdh.PrivateKey {
	t.Helper()
	k, err := ecdh.X25519().NewPrivateKey(unhex(t, s))
	if err != nil {
		t.Fatal(err)
	}
	return k
}

// TestVector replays the Cacophony test vector, checking this
// implementation against the byte-exact output of an independent one.
// Unlike the other tests here, which only check that the package
// interoperates with itself, this one would catch a deviation from
// the Noise specification: a wrong protocol name, a wrong nonce
// encoding, or a missing MixKey.
func TestVector(t *testing.T) {
	psk := unhex(t, vector.psk)
	prologue := unhex(t, vector.prologue)

	ihs, err := newHandshakeState(true, psk, prologue, ephemeral(t, vector.initEphemeral))
	if err != nil {
		t.Fatal(err)
	}
	rhs, err := newHandshakeState(false, psk, prologue, ephemeral(t, vector.respEphemeral))
	if err != nil {
		t.Fatal(err)
	}

	// The two handshake messages: initiator first, then responder.
	// Each side is fed the vector's ciphertext, not the bytes the
	// other side just produced, so both directions are checked.
	var ic1, ic2, rc1, rc2 *CipherState
	for i, hs := range []*HandshakeState{ihs, rhs} {
		peer := rhs
		if i == 1 {
			peer = ihs
		}
		want := unhex(t, vector.messages[i].ciphertext)
		payload := unhex(t, vector.messages[i].payload)

		msg, c1, c2, err := hs.WriteMessage(nil, payload)
		if err != nil {
			t.Fatalf("message %d WriteMessage: %v", i, err)
		}
		if !bytes.Equal(msg, want) {
			t.Fatalf("message %d = %x, want %x", i, msg, want)
		}
		pt, pc1, pc2, err := peer.ReadMessage(nil, want)
		if err != nil {
			t.Fatalf("message %d ReadMessage: %v", i, err)
		}
		if !bytes.Equal(pt, payload) {
			t.Fatalf("message %d payload = %x, want %x", i, pt, payload)
		}
		if i == 1 {
			rc1, rc2 = c1, c2
			ic1, ic2 = pc1, pc2
		}
	}

	if ic1 == nil || rc1 == nil {
		t.Fatal("handshake did not produce transport cipher states")
	}
	for _, hs := range []*HandshakeState{ihs, rhs} {
		if got := hex.EncodeToString(hs.ss.h); got != vector.handshakeHash {
			t.Errorf("handshake hash = %s, want %s", got, vector.handshakeHash)
		}
	}

	// The remaining vector messages are transport messages,
	// alternating initiator to responder and back.
	for i, m := range vector.messages[2:] {
		enc, dec := ic1, rc1 // initiator to responder
		if i%2 == 1 {
			enc, dec = rc2, ic2 // responder to initiator
		}
		want := unhex(t, m.ciphertext)
		payload := unhex(t, m.payload)

		ct, err := enc.Encrypt(nil, nil, payload)
		if err != nil {
			t.Fatalf("transport %d Encrypt: %v", i, err)
		}
		if !bytes.Equal(ct, want) {
			t.Fatalf("transport %d = %x, want %x", i, ct, want)
		}
		pt, err := dec.Decrypt(nil, nil, want)
		if err != nil {
			t.Fatalf("transport %d Decrypt: %v", i, err)
		}
		if !bytes.Equal(pt, payload) {
			t.Fatalf("transport %d payload = %x, want %x", i, pt, payload)
		}
	}
}
