// Code generated by "stringer -type StmtOp"; DO NOT EDIT.

package cc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StmtDecl-1]
	_ = x[StmtExpr-2]
	_ = x[Empty-3]
	_ = x[Block-4]
	_ = x[ARGBEGIN-5]
	_ = x[Break-6]
	_ = x[Continue-7]
	_ = x[Do-8]
	_ = x[For-9]
	_ = x[If-10]
	_ = x[Goto-11]
	_ = x[Return-12]
	_ = x[Switch-13]
	_ = x[While-14]
}

const _StmtOp_name = "StmtDeclStmtExprEmptyBlockARGBEGINBreakContinueDoForIfGotoReturnSwitchWhile"

var _StmtOp_index = [...]uint8{0, 8, 16, 21, 26, 34, 39, 47, 49, 52, 54, 58, 64, 70, 75}

func (i StmtOp) String() string {
	i -= 1
	if i < 0 || i >= StmtOp(len(_StmtOp_index)-1) {
		return "StmtOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _StmtOp_name[_StmtOp_index[i]:_StmtOp_index[i+1]]
}
