// Code generated by goyacc cc.y. DO NOT EDIT.

//line cc.y:34
package cc

import __yyfmt__ "fmt"

//line cc.y:34

type typeClass struct {
	c Storage
	q TypeQual
	t *Type
}

type idecor struct {
	d func(*Type) (*Type, string)
	i *Init
}

//line cc.y:49
type yySymType struct {
	yys      int
	abdecor  func(*Type) *Type
	decl     *Decl
	decls    []*Decl
	decor    func(*Type) (*Type, string)
	decors   []func(*Type) (*Type, string)
	expr     *Expr
	exprs    []*Expr
	idec     idecor
	idecs    []idecor
	init     *Init
	inits    []*Init
	label    *Label
	labels   []*Label
	span     Span
	prefix   *Prefix
	prefixes []*Prefix
	stmt     *Stmt
	stmts    []*Stmt
	str      string
	strs     []string
	tc       typeClass
	tk       TypeKind
	typ      *Type
}

const tokARGBEGIN = 57346
const tokARGEND = 57347
const tokAUTOLIB = 57348
const tokSET = 57349
const tokUSED = 57350
const tokAuto = 57351
const tokBreak = 57352
const tokCase = 57353
const tokChar = 57354
const tokConst = 57355
const tokContinue = 57356
const tokDefault = 57357
const tokDo = 57358
const tokDotDotDot = 57359
const tokDouble = 57360
const tokEnum = 57361
const tokError = 57362
const tokExtern = 57363
const tokFloat = 57364
const tokFor = 57365
const tokGoto = 57366
const tokIf = 57367
const tokInline = 57368
const tokInt = 57369
const tokLitChar = 57370
const tokLong = 57371
const tokName = 57372
const tokNumber = 57373
const tokOffsetof = 57374
const tokRegister = 57375
const tokReturn = 57376
const tokShort = 57377
const tokSigned = 57378
const tokStatic = 57379
const tokStruct = 57380
const tokSwitch = 57381
const tokTypeName = 57382
const tokTypedef = 57383
const tokUnion = 57384
const tokUnsigned = 57385
const tokVaArg = 57386
const tokVoid = 57387
const tokVolatile = 57388
const tokWhile = 57389
const tokString = 57390
const tokShift = 57391
const tokElse = 57392
const tokAddEq = 57393
const tokSubEq = 57394
const tokMulEq = 57395
const tokDivEq = 57396
const tokModEq = 57397
const tokLshEq = 57398
const tokRshEq = 57399
const tokAndEq = 57400
const tokXorEq = 57401
const tokOrEq = 57402
const tokOrOr = 57403
const tokAndAnd = 57404
const tokEqEq = 57405
const tokNotEq = 57406
const tokLtEq = 57407
const tokGtEq = 57408
const tokLsh = 57409
const tokRsh = 57410
const tokCast = 57411
const tokSizeof = 57412
const tokUnary = 57413
const tokDec = 57414
const tokInc = 57415
const tokArrow = 57416
const startExpr = 57417
const startProg = 57418
const tokEOF = 57419

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tokARGBEGIN",
	"tokARGEND",
	"tokAUTOLIB",
	"tokSET",
	"tokUSED",
	"tokAuto",
	"tokBreak",
	"tokCase",
	"tokChar",
	"tokConst",
	"tokContinue",
	"tokDefault",
	"tokDo",
	"tokDotDotDot",
	"tokDouble",
	"tokEnum",
	"tokError",
	"tokExtern",
	"tokFloat",
	"tokFor",
	"tokGoto",
	"tokIf",
	"tokInline",
	"tokInt",
	"tokLitChar",
	"tokLong",
	"tokName",
	"tokNumber",
	"tokOffsetof",
	"tokRegister",
	"tokReturn",
	"tokShort",
	"tokSigned",
	"tokStatic",
	"tokStruct",
	"tokSwitch",
	"tokTypeName",
	"tokTypedef",
	"tokUnion",
	"tokUnsigned",
	"tokVaArg",
	"tokVoid",
	"tokVolatile",
	"tokWhile",
	"tokString",
	"tokShift",
	"tokElse",
	"'{'",
	"','",
	"'='",
	"tokAddEq",
	"tokSubEq",
	"tokMulEq",
	"tokDivEq",
	"tokModEq",
	"tokLshEq",
	"tokRshEq",
	"tokAndEq",
	"tokXorEq",
	"tokOrEq",
	"'?'",
	"':'",
	"tokOrOr",
	"tokAndAnd",
	"'|'",
	"'^'",
	"'&'",
	"tokEqEq",
	"tokNotEq",
	"'<'",
	"'>'",
	"tokLtEq",
	"tokGtEq",
	"tokLsh",
	"tokRsh",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"tokCast",
	"'!'",
	"'~'",
	"tokSizeof",
	"tokUnary",
	"'.'",
	"'['",
	"']'",
	"'('",
	"')'",
	"tokDec",
	"tokInc",
	"tokArrow",
	"startExpr",
	"startProg",
	"tokEOF",
	"'}'",
	"';'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 118,
	52, 100,
	101, 100,
	-2, 180,
	-1, 136,
	51, 171,
	-2, 145,
	-1, 138,
	51, 171,
	-2, 150,
	-1, 238,
	101, 206,
	-2, 170,
	-1, 269,
	65, 171,
	-2, 91,
}

const yyPrivate = 57344

const yyLast = 1452

var yyAct = [...]int{

	309, 7, 112, 120, 342, 302, 259, 31, 225, 266,
	213, 279, 111, 240, 98, 99, 100, 101, 102, 103,
	104, 105, 106, 193, 196, 219, 117, 343, 237, 49,
	109, 5, 223, 123, 4, 217, 308, 133, 131, 377,
	129, 136, 138, 375, 227, 368, 367, 32, 363, 356,
	110, 354, 337, 336, 334, 289, 118, 288, 187, 305,
	34, 296, 140, 141, 142, 143, 144, 145, 146, 147,
	148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
	158, 130, 160, 161, 162, 163, 164, 165, 166, 167,
	168, 169, 170, 127, 292, 135, 244, 59, 210, 174,
	175, 249, 61, 62, 63, 64, 65, 159, 35, 295,
	3, 2, 96, 92, 380, 91, 184, 94, 93, 95,
	173, 124, 180, 96, 92, 374, 91, 124, 94, 93,
	95, 125, 190, 366, 365, 110, 364, 125, 176, 177,
	361, 128, 360, 134, 66, 67, 61, 62, 63, 64,
	65, 195, 189, 284, 188, 235, 96, 92, 189, 91,
	188, 94, 93, 95, 283, 252, 198, 197, 181, 189,
	199, 188, 121, 215, 130, 205, 203, 179, 256, 183,
	207, 178, 362, 122, 345, 344, 341, 339, 135, 257,
	333, 224, 226, 135, 230, 332, 212, 299, 115, 114,
	108, 221, 282, 6, 242, 211, 258, 207, 243, 204,
	210, 195, 224, 238, 348, 347, 291, 232, 233, 31,
	202, 216, 247, 208, 234, 221, 231, 274, 229, 290,
	376, 271, 254, 280, 281, 253, 134, 206, 60, 128,
	192, 134, 269, 246, 260, 250, 255, 226, 248, 238,
	208, 201, 200, 186, 277, 232, 116, 261, 97, 63,
	64, 65, 352, 267, 241, 263, 221, 96, 92, 57,
	91, 124, 94, 93, 95, 268, 294, 33, 185, 285,
	286, 125, 297, 301, 300, 293, 195, 270, 228, 287,
	298, 1, 52, 304, 269, 172, 57, 247, 37, 226,
	303, 11, 58, 194, 113, 230, 306, 132, 48, 56,
	126, 233, 312, 137, 139, 267, 55, 278, 317, 311,
	53, 313, 245, 338, 54, 335, 276, 119, 340, 58,
	171, 346, 272, 273, 264, 265, 239, 236, 230, 318,
	28, 26, 218, 191, 353, 29, 182, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	349, 350, 0, 0, 0, 371, 372, 373, 370, 355,
	0, 0, 357, 358, 0, 0, 0, 379, 0, 0,
	378, 381, 0, 0, 0, 0, 0, 0, 0, 0,
	369, 80, 81, 82, 83, 84, 85, 86, 87, 88,
	89, 90, 79, 359, 78, 77, 76, 75, 74, 72,
	73, 68, 69, 70, 71, 66, 67, 61, 62, 63,
	64, 65, 0, 0, 0, 0, 0, 96, 92, 0,
	91, 0, 94, 93, 95, 319, 0, 0, 316, 315,
	0, 320, 329, 0, 0, 321, 330, 322, 0, 0,
	0, 0, 0, 0, 323, 324, 325, 0, 0, 10,
	0, 331, 9, 21, 0, 326, 0, 0, 0, 0,
	327, 0, 0, 0, 0, 23, 0, 0, 328, 24,
	0, 0, 260, 74, 72, 73, 68, 69, 70, 71,
	66, 67, 61, 62, 63, 64, 65, 0, 0, 0,
	0, 13, 96, 92, 0, 91, 0, 94, 93, 95,
	14, 15, 12, 0, 0, 0, 16, 17, 20, 0,
	0, 0, 0, 22, 0, 19, 18, 0, 0, 0,
	0, 0, 314, 80, 81, 82, 83, 84, 85, 86,
	87, 88, 89, 90, 79, 0, 78, 77, 76, 75,
	74, 72, 73, 68, 69, 70, 71, 66, 67, 61,
	62, 63, 64, 65, 0, 0, 0, 0, 0, 96,
	92, 307, 91, 0, 94, 93, 95, 80, 81, 82,
	83, 84, 85, 86, 87, 88, 89, 90, 79, 0,
	78, 77, 76, 75, 74, 72, 73, 68, 69, 70,
	71, 66, 67, 61, 62, 63, 64, 65, 0, 0,
	0, 0, 0, 96, 92, 0, 91, 275, 94, 93,
	95, 214, 80, 81, 82, 83, 84, 85, 86, 87,
	88, 89, 90, 79, 0, 78, 77, 76, 75, 74,
	72, 73, 68, 69, 70, 71, 66, 67, 61, 62,
	63, 64, 65, 0, 0, 0, 0, 0, 96, 92,
	0, 91, 0, 94, 93, 95, 80, 81, 82, 83,
	84, 85, 86, 87, 88, 89, 90, 79, 0, 78,
	77, 76, 75, 74, 72, 73, 68, 69, 70, 71,
	66, 67, 61, 62, 63, 64, 65, 0, 0, 0,
	0, 0, 96, 92, 0, 91, 0, 94, 93, 95,
	52, 0, 0, 39, 57, 0, 0, 0, 0, 46,
	38, 0, 113, 45, 0, 0, 0, 56, 41, 10,
	42, 8, 9, 21, 55, 0, 40, 43, 53, 50,
	0, 36, 54, 51, 44, 23, 47, 58, 0, 24,
	77, 76, 75, 74, 72, 73, 68, 69, 70, 71,
	66, 67, 61, 62, 63, 64, 65, 0, 0, 0,
	0, 13, 96, 92, 0, 91, 0, 94, 93, 95,
	14, 15, 12, 0, 0, 0, 16, 17, 20, 0,
	0, 27, 0, 22, 52, 19, 18, 39, 57, 0,
	0, 0, 0, 46, 38, 0, 30, 45, 0, 0,
	0, 56, 41, 0, 42, 0, 0, 0, 55, 0,
	40, 43, 53, 50, 0, 36, 54, 51, 44, 52,
	47, 58, 39, 57, 0, 0, 0, 0, 46, 38,
	0, 113, 45, 0, 0, 0, 56, 41, 0, 42,
	0, 0, 0, 55, 0, 40, 43, 53, 50, 0,
	36, 54, 51, 44, 52, 47, 58, 39, 57, 0,
	0, 0, 0, 46, 38, 0, 113, 45, 0, 0,
	0, 56, 41, 0, 42, 251, 0, 0, 55, 0,
	40, 43, 53, 50, 0, 36, 54, 51, 44, 0,
	47, 58, 27, 0, 0, 52, 0, 0, 39, 57,
	0, 0, 0, 0, 46, 38, 0, 30, 45, 0,
	310, 0, 56, 41, 0, 42, 0, 0, 0, 55,
	0, 40, 43, 53, 50, 0, 36, 54, 51, 44,
	0, 47, 58, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 79, 262, 78, 77, 76, 75,
	74, 72, 73, 68, 69, 70, 71, 66, 67, 61,
	62, 63, 64, 65, 0, 0, 0, 0, 0, 96,
	92, 0, 91, 0, 94, 93, 95, 0, 0, 0,
	0, 0, 0, 0, 0, 25, 76, 75, 74, 72,
	73, 68, 69, 70, 71, 66, 67, 61, 62, 63,
	64, 65, 0, 0, 0, 0, 0, 96, 92, 0,
	91, 0, 94, 93, 95, 75, 74, 72, 73, 68,
	69, 70, 71, 66, 67, 61, 62, 63, 64, 65,
	0, 0, 0, 0, 0, 96, 92, 0, 91, 0,
	94, 93, 95, 72, 73, 68, 69, 70, 71, 66,
	67, 61, 62, 63, 64, 65, 10, 0, 8, 9,
	21, 96, 92, 0, 91, 0, 94, 93, 95, 0,
	0, 0, 23, 0, 0, 0, 24, 0, 0, 209,
	0, 0, 73, 68, 69, 70, 71, 66, 67, 61,
	62, 63, 64, 65, 0, 0, 0, 0, 13, 96,
	92, 0, 91, 0, 94, 93, 95, 14, 15, 12,
	0, 0, 0, 16, 17, 20, 0, 280, 281, 0,
	22, 0, 19, 18, 68, 69, 70, 71, 66, 67,
	61, 62, 63, 64, 65, 10, 0, 8, 9, 21,
	96, 92, 0, 91, 0, 94, 93, 95, 0, 0,
	0, 23, 0, 0, 0, 24, 0, 0, 209, 0,
	0, 0, 10, 0, 8, 9, 21, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 13, 23, 0,
	0, 0, 24, 0, 0, 0, 14, 15, 12, 0,
	0, 0, 16, 17, 20, 0, 0, 0, 0, 22,
	0, 19, 18, 0, 13, 0, 0, 10, 0, 8,
	9, 21, 0, 14, 15, 12, 0, 0, 0, 16,
	17, 20, 0, 23, 0, 0, 22, 24, 19, 18,
	10, 0, 8, 9, 21, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 23, 0, 0, 13,
	24, 0, 0, 209, 0, 0, 0, 0, 14, 15,
	12, 0, 0, 0, 16, 17, 20, 0, 0, 0,
	0, 107, 0, 19, 18, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 16, 17, 20,
	0, 0, 0, 0, 22, 52, 19, 18, 39, 57,
	0, 0, 0, 222, 46, 38, 0, 113, 45, 0,
	0, 0, 56, 41, 0, 42, 220, 0, 0, 55,
	0, 40, 43, 53, 50, 0, 36, 54, 51, 44,
	351, 47, 58, 0, 52, 0, 0, 39, 57, 0,
	0, 0, 0, 46, 38, 0, 113, 45, 0, 0,
	0, 56, 41, 0, 42, 0, 0, 0, 55, 0,
	40, 43, 53, 50, 0, 36, 54, 51, 44, 52,
	47, 58, 39, 57, 0, 0, 0, 0, 46, 38,
	0, 113, 45, 0, 0, 0, 56, 41, 0, 42,
	0, 0, 0, 55, 0, 40, 43, 53, 50, 0,
	36, 54, 51, 44, 52, 47, 58, 39, 57, 0,
	0, 0, 0, 46, 0, 0, 113, 45, 0, 0,
	0, 56, 41, 0, 42, 0, 0, 0, 55, 0,
	40, 43, 53, 0, 0, 0, 54, 0, 44, 0,
	47, 58,
}
var yyPact = [...]int{

	13, -1000, -1000, 1144, 896, -2, 186, 613, -1000, -1000,
	-1000, 210, 1144, 1144, 1144, 1144, 1144, 1144, 1144, 1144,
	1189, 108, 701, 107, -1000, -1000, -1000, 106, -1000, -1000,
	208, 91, 1370, 283, 1405, -1000, -1000, 241, 241, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	1144, 1144, 1144, 1144, 1144, 1144, 1144, 1144, 1144, 1144,
	1144, 1144, 1144, 1144, 1144, 1144, 1144, 1144, 1144, 1144,
	1144, 1144, 1144, 1144, 1144, 1144, 1144, 1144, 1144, 1144,
	1144, 1144, 1144, -1000, -1000, 241, 241, -1000, 34, 34,
	34, 34, 34, 34, 34, 34, 34, 701, 1370, 88,
	84, 87, -1000, -1000, 1144, 248, 202, -43, 79, 188,
	-1000, 256, 91, -1000, -1000, -1000, 283, 1405, -1000, -1000,
	283, -1000, 1405, -1000, -1000, -1000, -1000, 201, -1000, 200,
	613, 178, 178, 34, 34, 34, 23, 23, 67, 67,
	67, 67, 1020, 1061, 982, 413, 956, 928, 683, 155,
	613, 613, 613, 613, 613, 613, 613, 613, 613, 613,
	613, 83, 186, 118, -1000, -1000, 82, 185, 1117, -1000,
	120, 256, 104, 87, 569, 80, -1000, -1000, 1296, 1144,
	1117, 1370, 91, 91, 256, -1000, 62, -1000, -1000, -1000,
	1370, 234, 1144, -1000, -1000, 1212, 1144, 34, -1000, -4,
	1144, 87, 1296, 8, 1370, -1000, 785, 72, 183, -1000,
	-1000, 97, -1000, 115, 613, -1000, 613, -1000, 193, -1000,
	91, -1000, 79, 68, -1000, -1000, 855, -1000, 91, 179,
	-1000, 174, 890, 524, -1000, 1038, 111, 120, 71, -1000,
	60, -1000, -1000, 1296, 120, 68, 256, 97, -1000, -1000,
	-1000, -44, -1000, -1000, -46, 177, -1000, 68, 151, -1000,
	-6, 234, -1000, -1000, 1144, -1000, 9, -1000, 144, -1000,
	241, 1144, -1000, -1000, -1000, -1000, 97, -1000, -1000, -1000,
	91, 1144, -1000, -1000, 613, -1000, -41, 1117, -1000, -1000,
	-1000, 480, 820, -1000, 613, -1000, -1000, -1000, -1000, -1000,
	-1000, 431, -1000, -1000, -1000, 103, 98, -1000, -47, -1000,
	-48, -49, -1000, 95, 241, 94, 1144, 93, 92, 1144,
	150, 149, 1144, 1144, -1000, 1335, -1000, -1000, 215, 1144,
	-50, 1144, -52, -1000, 1144, 1144, 338, -1000, -1000, 49,
	47, -1000, 90, -53, -1000, 43, -1000, 41, 40, -1000,
	-55, -56, 1144, 1144, -1000, -1000, -1000, -1000, -1000, 32,
	-58, 180, -1000, -1000, -62, 1144, -1000, -1000, 21, -1000,
	-1000, -1000,
}
var yyPgo = [...]int{

	0, 10, 346, 25, 345, 13, 36, 343, 342, 35,
	34, 341, 340, 28, 337, 336, 24, 9, 335, 334,
	1, 32, 27, 4, 333, 332, 203, 330, 33, 327,
	26, 8, 326, 44, 322, 321, 319, 11, 317, 312,
	6, 0, 5, 308, 29, 60, 108, 37, 3, 275,
	47, 40, 307, 38, 303, 23, 301, 2, 298, 30,
	12, 277, 291, 289, 288, 287, 282,
}
var yyR1 = [...]int{

	0, 62, 62, 10, 10, 10, 22, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	42, 42, 42, 63, 40, 35, 35, 35, 41, 39,
	39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
	39, 39, 39, 39, 39, 1, 1, 1, 2, 2,
	2, 16, 16, 16, 16, 16, 3, 3, 3, 3,
	28, 28, 43, 43, 43, 43, 43, 43, 44, 44,
	45, 45, 45, 45, 45, 45, 45, 45, 45, 46,
	46, 47, 47, 61, 57, 57, 57, 57, 57, 60,
	59, 6, 12, 11, 11, 11, 64, 4, 48, 48,
	58, 58, 17, 17, 13, 61, 61, 37, 20, 20,
	61, 61, 5, 24, 31, 31, 33, 33, 33, 34,
	34, 32, 32, 37, 66, 66, 65, 65, 38, 38,
	49, 49, 23, 23, 21, 21, 26, 26, 27, 27,
	7, 7, 36, 36, 8, 8, 9, 9, 29, 29,
	30, 30, 54, 54, 55, 55, 50, 50, 51, 51,
	52, 52, 53, 53, 18, 18, 19, 19, 14, 14,
	25, 25, 15, 15, 56, 56,
}
var yyR2 = [...]int{

	0, 3, 3, 0, 2, 5, 1, 1, 1, 1,
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 5,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	4, 6, 4, 4, 3, 4, 4, 2, 2, 6,
	0, 2, 2, 0, 4, 3, 2, 2, 2, 1,
	5, 5, 1, 2, 3, 2, 2, 7, 9, 3,
	5, 7, 3, 5, 5, 0, 3, 1, 4, 4,
	3, 1, 3, 3, 4, 4, 1, 2, 2, 1,
	1, 3, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 3, 3, 2, 2, 1,
	2, 3, 3, 1, 1, 5, 0, 5, 1, 1,
	1, 1, 1, 3, 3, 2, 5, 2, 3, 3,
	2, 6, 2, 2, 1, 1, 2, 4, 5, 0,
	3, 1, 3, 3, 0, 1, 0, 1, 1, 2,
	0, 1, 0, 1, 0, 1, 1, 3, 0, 1,
	0, 2, 0, 2, 1, 3, 0, 1, 1, 3,
	0, 1, 1, 2, 0, 1, 1, 2, 0, 1,
	1, 2, 0, 1, 1, 3, 0, 1, 1, 2,
	0, 1, 1, 3, 1, 2,
}
var yyChk = [...]int{

	-1000, -62, 98, 97, -10, -22, -26, -20, 30, 31,
	28, -56, 81, 70, 79, 80, 85, 86, 95, 94,
	87, 32, 92, 44, 48, 99, -11, 6, -12, -4,
	21, -57, -50, -61, -45, -46, 40, -58, 19, 12,
	35, 27, 29, 36, 43, 22, 18, 45, -43, -44,
	38, 42, 9, 37, 41, 33, 26, 13, 46, 99,
	52, 79, 80, 81, 82, 83, 77, 78, 73, 74,
	75, 76, 71, 72, 70, 69, 68, 67, 66, 64,
	53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
	63, 92, 90, 95, 94, 96, 89, 48, -20, -20,
	-20, -20, -20, -20, -20, -20, -20, 92, 92, -59,
	-22, -60, -57, 21, 92, 92, 48, -30, -16, -29,
	-48, 81, 92, -28, 30, 40, -61, -45, -46, -51,
	-50, -53, -52, -47, -46, -45, -48, -49, -48, -49,
	-20, -20, -20, -20, -20, -20, -20, -20, -20, -20,
	-20, -20, -20, -20, -20, -20, -20, -20, -20, -22,
	-20, -20, -20, -20, -20, -20, -20, -20, -20, -20,
	-20, -27, -26, -22, -48, -48, -59, -59, 93, 93,
	-1, 81, -2, 92, -20, 30, 51, 101, 92, 90,
	53, -7, 52, -55, -54, -44, -16, -51, -53, -47,
	51, 51, 65, 93, 91, 93, 52, -20, -33, 51,
	90, -55, 92, -1, 52, 93, -10, -9, -8, -3,
	30, -60, 17, -21, -20, -31, -20, -33, -64, -6,
	-57, -28, -16, -16, -44, 93, -14, -13, -60, -15,
	-5, 30, -20, -20, 100, -34, -21, -1, -9, 93,
	-59, 100, 93, 52, -1, -16, 81, 92, 91, -40,
	51, -30, 100, -13, -19, -18, -17, -16, -49, -48,
	-65, 52, -25, -24, 53, 93, -32, -31, -38, -37,
	89, 90, 91, 93, 93, -3, -55, -63, 101, 101,
	52, 65, 100, -5, -20, 100, 52, -66, -37, 53,
	-48, -20, -42, -17, -20, 100, -31, 91, -6, -41,
	100, -36, -39, -35, 101, 8, 7, -40, -22, 4,
	10, 14, 16, 23, 24, 25, 34, 39, 47, 11,
	15, 30, 92, 92, 101, -42, 101, 101, -41, 92,
	-48, 92, -23, -22, 92, 92, -20, 65, 65, -22,
	-22, 5, 47, -23, 101, -22, 101, -22, -22, 65,
	93, 93, 92, 101, 93, 93, 93, 101, 101, -22,
	-23, -41, -41, -41, 93, 101, 50, 101, -23, -41,
	93, -41,
}
var yyDef = [...]int{

	0, -2, 3, 0, 0, 0, 6, 176, 7, 8,
	9, 10, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 214, 1, 4, 0, 133, 134,
	104, 190, 124, 198, 202, 196, 123, 170, 170, 110,
	111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
	140, 141, 102, 103, 105, 106, 107, 108, 109, 2,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 178, 0, 57, 58, 0, 0, 215, 41, 42,
	43, 44, 45, 46, 47, 48, 49, 0, 0, 0,
	0, 85, 129, 104, 0, 0, 0, 0, -2, 191,
	91, 194, 0, 188, 138, 139, 198, 202, 197, 127,
	199, 128, 203, 200, 121, 122, -2, 0, -2, 0,
	177, 11, 12, 13, 14, 15, 16, 17, 18, 19,
	20, 21, 22, 23, 24, 25, 26, 27, 28, 0,
	30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
	40, 0, 179, 0, 148, 149, 0, 0, 0, 54,
	130, 194, 87, 85, 0, 0, 3, 132, 186, 174,
	0, 136, 0, 0, 195, 192, 0, 125, 126, 201,
	0, 0, 0, 55, 56, 50, 0, 52, 53, 159,
	174, 85, 186, 0, 0, 5, 0, 0, 187, 184,
	96, 85, 99, 0, 175, 101, 154, 155, 0, 181,
	190, 189, 100, 92, 193, 93, 0, 208, -2, 166,
	212, 210, 29, 0, 156, 0, 0, 86, 0, 90,
	0, 135, 94, 0, 97, 98, 194, 85, 95, 137,
	63, 0, 146, 209, 0, 207, 204, 142, 0, -2,
	0, 167, 152, 211, 0, 51, 0, 161, 164, 168,
	0, 0, 89, 88, 59, 185, 85, 60, 131, 144,
	170, 0, 151, 213, 153, 157, 160, 0, 169, 165,
	147, 0, 182, 205, 143, 158, 162, 163, 61, 62,
	64, 0, 68, 183, 69, 0, 0, 72, 0, 60,
	0, 0, 182, 0, 0, 0, 172, 0, 0, 0,
	0, 7, 0, 0, 73, 182, 75, 76, 0, 172,
	0, 0, 0, 173, 0, 0, 0, 66, 67, 0,
	0, 74, 0, 0, 79, 0, 82, 0, 0, 65,
	0, 0, 0, 172, 182, 182, 182, 70, 71, 0,
	0, 80, 83, 84, 0, 172, 182, 77, 0, 81,
	182, 78,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 85, 3, 3, 3, 83, 70, 3,
	92, 93, 81, 79, 52, 80, 89, 82, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 65, 101,
	73, 53, 74, 64, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 90, 3, 91, 69, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 51, 68, 100, 86,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 54,
	55, 56, 57, 58, 59, 60, 61, 62, 63, 66,
	67, 71, 72, 75, 76, 77, 78, 84, 87, 88,
	94, 95, 96, 97, 98, 99,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:185
		{
			yylex.(*lexer).prog = &Prog{Decls: yyDollar[2].decls}
			return 0
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:190
		{
			yylex.(*lexer).expr = yyDollar[2].expr
			return 0
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:196
		{
			yyVAL.span = Span{}
			yyVAL.decls = nil
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:201
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.decls = append(yyDollar[1].decls, yyDollar[2].decls...)
		}
	case 5:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:206
		{
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:211
		{
			yyVAL.span = yyDollar[1].span
			if len(yyDollar[1].exprs) == 1 {
				yyVAL.expr = yyDollar[1].exprs[0]
				break
			}
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Comma, List: yyDollar[1].exprs}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:222
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Name, Text: yyDollar[1].str, XDecl: yyDollar[1].decl}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:227
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Number, Text: yyDollar[1].str}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:232
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Number, Text: yyDollar[1].str}
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:237
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: String, Texts: yyDollar[1].strs}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:242
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Add, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:247
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Sub, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:252
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Mul, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:257
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Div, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:262
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Mod, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:267
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Lsh, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:272
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Rsh, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:277
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Lt, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:282
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Gt, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:287
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: LtEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:292
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: GtEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:297
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: EqEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:302
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: NotEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:307
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: And, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:312
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Xor, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:317
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Or, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:322
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: AndAnd, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:327
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: OrOr, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 29:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:332
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[5].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Cond, List: []*Expr{yyDollar[1].expr, yyDollar[3].expr, yyDollar[5].expr}}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:337
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Eq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:342
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: AddEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:347
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: SubEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:352
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: MulEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:357
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: DivEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:362
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: ModEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:367
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: LshEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:372
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: RshEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:377
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: AndEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:382
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: XorEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:387
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: OrEq, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:392
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Indir, Left: yyDollar[2].expr}
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:397
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Addr, Left: yyDollar[2].expr}
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:402
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Plus, Left: yyDollar[2].expr}
		}
	case 44:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:407
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Minus, Left: yyDollar[2].expr}
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:412
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Not, Left: yyDollar[2].expr}
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:417
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Twid, Left: yyDollar[2].expr}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:422
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: PreInc, Left: yyDollar[2].expr}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:427
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: PreDec, Left: yyDollar[2].expr}
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:432
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: SizeofExpr, Left: yyDollar[2].expr}
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:437
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: SizeofType, Type: yyDollar[3].typ}
		}
	case 51:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cc.y:442
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[6].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Offsetof, Type: yyDollar[3].typ, Left: yyDollar[5].expr}
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:447
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Cast, Type: yyDollar[2].typ, Left: yyDollar[4].expr}
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:452
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: CastInit, Type: yyDollar[2].typ, Init: &Init{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Braced: yyDollar[4].inits}}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:457
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Paren, Left: yyDollar[2].expr}
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:462
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Call, Left: yyDollar[1].expr, List: yyDollar[3].exprs}
		}
	case 56:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:467
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Index, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:472
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: PostInc, Left: yyDollar[1].expr}
		}
	case 58:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:477
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: PostDec, Left: yyDollar[1].expr}
		}
	case 59:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cc.y:482
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[6].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: VaArg, Left: yyDollar[3].expr, Type: yyDollar[5].typ}
		}
	case 60:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:488
		{
			yyVAL.span = Span{}
			yyVAL.stmts = nil
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:493
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.stmts = yyDollar[1].stmts
			for _, d := range yyDollar[2].decls {
				yyVAL.stmts = append(yyVAL.stmts, &Stmt{SyntaxInfo: SyntaxInfo{Span: d.Span}, Op: StmtDecl, Decl: d})
			}
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:501
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:508
		{
			yylex.(*lexer).pushScope()
		}
	case 64:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:512
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			yyDollar[3].stmts = append([]*Stmt{&Stmt{SyntaxInfo: SyntaxInfo{Span: yyDollar[1].span}, Op: Empty}}, yyDollar[3].stmts...)
			yyDollar[3].stmts = append(yyDollar[3].stmts, &Stmt{SyntaxInfo: SyntaxInfo{Span: yyDollar[4].span}, Op: Empty})
			yylex.(*lexer).popScope()
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Block, Block: yyDollar[3].stmts}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:522
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.label = &Label{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Case, Expr: yyDollar[2].expr}
		}
	case 66:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:527
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.label = &Label{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Default}
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:532
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.label = &Label{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: LabelName, Name: yyDollar[1].str}
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:539
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.stmt = yyDollar[2].stmt
			yyVAL.stmt.Labels = yyDollar[1].labels
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:547
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Empty}
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:552
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Empty}
		}
	case 71:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:557
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Empty}
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:562
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:567
		{
			first := yyDollar[1].expr
			if yyDollar[1].expr.Op == Comma {
				first = yyDollar[1].expr.List[0]
			}
			if first.Op == Mul && first.Left.Op == Name {
				yylex.Error("likely type near " + first.Left.Text)
			}
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: StmtExpr, Expr: yyDollar[1].expr}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:579
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: ARGBEGIN, Block: yyDollar[2].stmts}
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:584
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Break}
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:589
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Continue}
		}
	case 77:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cc.y:594
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[7].span)
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Do, Body: yyDollar[2].stmt, Expr: yyDollar[5].expr}
		}
	case 78:
		yyDollar = yyS[yypt-9 : yypt+1]
//line cc.y:599
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[9].span)
			if yyDollar[9].stmt.Op != Block {
				yyDollar[9].stmt = &Stmt{
					SyntaxInfo: SyntaxInfo{Span: Span{yyDollar[8].span.End, yyDollar[9].span.End}},
					Op:         Block,
					Block: []*Stmt{
						&Stmt{SyntaxInfo: SyntaxInfo{Span: Span{yyDollar[8].span.End, yyDollar[8].span.End}}, Op: Empty},
						yyDollar[9].stmt,
						&Stmt{SyntaxInfo: SyntaxInfo{Span: Span{yyDollar[9].span.End, yyDollar[9].span.End}}, Op: Empty},
					},
				}
			}
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span},
				Op:   For,
				Pre:  yyDollar[3].expr,
				Expr: yyDollar[5].expr,
				Post: yyDollar[7].expr,
				Body: yyDollar[9].stmt,
			}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:621
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Goto, Text: yyDollar[2].str}
		}
	case 80:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:626
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[5].span)
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: If, Expr: yyDollar[3].expr, Body: yyDollar[5].stmt}
		}
	case 81:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cc.y:631
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[7].span)
			if yyDollar[7].stmt.Op != Block && yyDollar[7].stmt.Op != If {
				yyDollar[7].stmt = &Stmt{
					SyntaxInfo: SyntaxInfo{Span: Span{yyDollar[6].span.End, yyDollar[7].span.End}},
					Op:         Block,
					Block: []*Stmt{
						&Stmt{SyntaxInfo: SyntaxInfo{Span: Span{yyDollar[6].span.End, yyDollar[6].span.End}}, Op: Empty},
						yyDollar[7].stmt,
						&Stmt{SyntaxInfo: SyntaxInfo{Span: Span{yyDollar[7].span.End, yyDollar[7].span.End}}, Op: Empty},
					},
				}
			}
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: If, Expr: yyDollar[3].expr, Body: yyDollar[5].stmt, Else: yyDollar[7].stmt}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:647
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Return, Expr: yyDollar[2].expr}
		}
	case 83:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:652
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[5].span)
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Switch, Expr: yyDollar[3].expr, Body: yyDollar[5].stmt}
		}
	case 84:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:657
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[5].span)
			yyVAL.stmt = &Stmt{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: While, Expr: yyDollar[3].expr, Body: yyDollar[5].stmt}
		}
	case 85:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:664
		{
			yyVAL.span = Span{}
			yyVAL.abdecor = func(t *Type) *Type { return t }
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:669
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			_, q, _ := splitTypeWords(yyDollar[2].strs)
			abdecor := yyDollar[3].abdecor
			yyVAL.abdecor = func(t *Type) *Type {
				return abdecor(&Type{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Kind: Ptr, Base: t, Qual: q})
			}
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:678
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.abdecor = yyDollar[1].abdecor
		}
	case 88:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:685
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			abdecor := yyDollar[1].abdecor
			decls := yyDollar[3].decls
			span := yyVAL.span
			for _, decl := range decls {
				t := decl.Type
				if t != nil {
					if t.Kind == TypedefType && t.Base != nil {
						t = t.Base
					}
					if t.Kind == Array {
						if t.Width == nil {
							t = t.Base
						}
						decl.Type = &Type{Kind: Ptr, Base: t}
					}
				}
			}
			yyVAL.abdecor = func(t *Type) *Type {
				return abdecor(&Type{SyntaxInfo: SyntaxInfo{Span: span}, Kind: Func, Base: t, Decls: decls})
			}
		}
	case 89:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:709
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			abdecor := yyDollar[1].abdecor
			span := yyVAL.span
			expr := yyDollar[3].expr
			yyVAL.abdecor = func(t *Type) *Type {
				return abdecor(&Type{SyntaxInfo: SyntaxInfo{Span: span}, Kind: Array, Base: t, Width: expr})
			}

		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:720
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.abdecor = yyDollar[2].abdecor
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:728
		{
			yyVAL.span = yyDollar[1].span
			name := yyDollar[1].str
			yyVAL.decor = func(t *Type) (*Type, string) { return t, name }
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:734
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			_, q, _ := splitTypeWords(yyDollar[2].strs)
			decor := yyDollar[3].decor
			span := yyVAL.span
			yyVAL.decor = func(t *Type) (*Type, string) {
				return decor(&Type{SyntaxInfo: SyntaxInfo{Span: span}, Kind: Ptr, Base: t, Qual: q})
			}
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:744
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.decor = yyDollar[2].decor
		}
	case 94:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:749
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			decor := yyDollar[1].decor
			decls := yyDollar[3].decls
			span := yyVAL.span
			yyVAL.decor = func(t *Type) (*Type, string) {
				return decor(&Type{SyntaxInfo: SyntaxInfo{Span: span}, Kind: Func, Base: t, Decls: decls})
			}
		}
	case 95:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:759
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			decor := yyDollar[1].decor
			span := yyVAL.span
			expr := yyDollar[3].expr
			yyVAL.decor = func(t *Type) (*Type, string) {
				return decor(&Type{SyntaxInfo: SyntaxInfo{Span: span}, Kind: Array, Base: t, Width: expr})
			}
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:772
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decl = &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Name: yyDollar[1].str}
		}
	case 97:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:777
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.decl = &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Type: yyDollar[2].abdecor(yyDollar[1].typ)}
		}
	case 98:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:782
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			typ, name := yyDollar[2].decor(yyDollar[1].typ)
			yyVAL.decl = &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Name: name, Type: typ}
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:788
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decl = &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Name: "..."}
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:796
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.idec = idecor{yyDollar[1].decor, nil}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:801
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.idec = idecor{yyDollar[1].decor, yyDollar[3].init}
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:809
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:814
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:819
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:824
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:829
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:834
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:842
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:847
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:855
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:860
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:865
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:870
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:875
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:880
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:885
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 117:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:890
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:895
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:902
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:907
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:914
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:919
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:927
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.typ = yyDollar[1].typ
			if yyVAL.typ == nil {
				yyVAL.typ = &Type{Kind: TypedefType, Name: yyDollar[1].str}
			}
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:943
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.tc.c, yyVAL.tc.q, yyVAL.tc.t = splitTypeWords(append(yyDollar[1].strs, "int"))
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:948
		{
			yyVAL.span = span(span(yyDollar[1].span, yyDollar[2].span), yyDollar[3].span)
			yyVAL.tc.c, yyVAL.tc.q, _ = splitTypeWords(append(yyDollar[1].strs, yyDollar[3].strs...))
			yyVAL.tc.t = yyDollar[2].typ
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:954
		{
			yyVAL.span = span(span(yyDollar[1].span, yyDollar[2].span), yyDollar[3].span)
			yyDollar[1].strs = append(yyDollar[1].strs, yyDollar[2].str)
			yyDollar[1].strs = append(yyDollar[1].strs, yyDollar[3].strs...)
			yyVAL.tc.c, yyVAL.tc.q, yyVAL.tc.t = splitTypeWords(yyDollar[1].strs)
		}
	case 127:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:961
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.tc.c, yyVAL.tc.q, _ = splitTypeWords(yyDollar[2].strs)
			yyVAL.tc.t = yyDollar[1].typ
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:967
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			var ts []string
			ts = append(ts, yyDollar[1].str)
			ts = append(ts, yyDollar[2].strs...)
			yyVAL.tc.c, yyVAL.tc.q, yyVAL.tc.t = splitTypeWords(ts)
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:978
		{
			yyVAL.span = yyDollar[1].span
			if yyDollar[1].tc.c != 0 {
				yylex.(*lexer).Errorf("%v not allowed here", yyDollar[1].tc.c)
			}
			if yyDollar[1].tc.q != 0 && yyDollar[1].tc.q != Const && yyDollar[1].tc.q != Volatile {
				yylex.(*lexer).Errorf("%v ignored here (TODO)?", yyDollar[1].tc.q)
			}
			yyVAL.typ = yyDollar[1].tc.t
		}
	case 130:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:991
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.typ = yyDollar[2].abdecor(yyDollar[1].typ)
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:999
		{
			lx := yylex.(*lexer)
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			// TODO: use $1.q
			yyVAL.decls = nil
			for _, idec := range yyDollar[2].idecs {
				typ, name := idec.d(yyDollar[1].tc.t)
				d := &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Name: name, Type: typ, Storage: yyDollar[1].tc.c, Init: idec.i}
				lx.pushDecl(d)
				yyVAL.decls = append(yyVAL.decls, d)
			}
			if yyDollar[2].idecs == nil {
				d := &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Name: "", Type: yyDollar[1].tc.t, Storage: yyDollar[1].tc.c}
				lx.pushDecl(d)
				yyVAL.decls = append(yyVAL.decls, d)
			}
		}
	case 132:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1019
		{
			lx := yylex.(*lexer)
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			// TODO: use $1.q
			yyVAL.decls = nil
			for _, idec := range yyDollar[2].idecs {
				typ, name := idec.d(yyDollar[1].tc.t)
				d := lx.lookupDecl(name)
				if d == nil {
					d = &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Name: name, Type: typ, Storage: yyDollar[1].tc.c, Init: idec.i}
					lx.pushDecl(d)
				} else {
					d.Span = yyVAL.span
					if idec.i != nil {
						d.Init = idec.i
					}
				}
				yyVAL.decls = append(yyVAL.decls, d)
			}
			if yyDollar[2].idecs == nil {
				d := &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Name: "", Type: yyDollar[1].tc.t, Storage: yyDollar[1].tc.c}
				lx.pushDecl(d)
				yyVAL.decls = append(yyVAL.decls, d)
			}
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1047
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decls = yyDollar[1].decls
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1052
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decls = []*Decl{yyDollar[1].decl}
		}
	case 135:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:1057
		{
			yyVAL.decls = yyDollar[4].decls
		}
	case 136:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1063
		{
			lx := yylex.(*lexer)
			typ, name := yyDollar[2].decor(yyDollar[1].tc.t)
			if typ.Kind != Func {

				yylex.(*lexer).Errorf("invalid function definition for %s", name)
				return 0
			}
			d := lx.lookupDecl(name)
			if d == nil {
				d = &Decl{Name: name, Type: typ, Storage: yyDollar[1].tc.c}
				lx.pushDecl(d)
			} else {
				d.Type = typ
			}
			yyVAL.decl = d
			lx.pushScope()
			for _, decl := range typ.Decls {
				lx.pushDecl(decl)
			}
		}
	case 137:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:1085
		{
			yylex.(*lexer).popScope()
			yyVAL.span = span(yyDollar[1].span, yyDollar[5].span)
			yyVAL.decl = yyDollar[4].decl
			yyVAL.decl.Span = yyVAL.span
			if yyDollar[3].decls != nil {
				yylex.(*lexer).Errorf("cannot use pre-prototype definitions")
			}
			yyVAL.decl.Body = yyDollar[5].stmt
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1098
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1103
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1111
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.tk = Struct
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1116
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.tk = Union
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1123
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decor = yyDollar[1].decor
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1128
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			name := yyDollar[1].str
			expr := yyDollar[3].expr
			yyVAL.decor = func(t *Type) (*Type, string) {
				t.Width = expr
				return t, name
			}
		}
	case 144:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1140
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.decls = nil
			for _, decor := range yyDollar[2].decors {
				typ, name := decor(yyDollar[1].typ)
				yyVAL.decls = append(yyVAL.decls, &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Name: name, Type: typ})
			}
			if yyDollar[2].decors == nil {
				yyVAL.decls = append(yyVAL.decls, &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Type: yyDollar[1].typ})
			}
		}
	case 145:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1154
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.typ = yylex.(*lexer).pushType(&Type{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Kind: yyDollar[1].tk, Tag: yyDollar[2].str})
		}
	case 146:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:1159
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[5].span)
			yyVAL.typ = yylex.(*lexer).pushType(&Type{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Kind: yyDollar[1].tk, Tag: yyDollar[2].str, Decls: yyDollar[4].decls})
		}
	case 147:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1166
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.prefix = &Prefix{Span: yyVAL.span, Dot: yyDollar[2].str}
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1173
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Arrow, Left: yyDollar[1].expr, Text: yyDollar[3].str}
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1178
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.expr = &Expr{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Op: Dot, Left: yyDollar[1].expr, Text: yyDollar[3].str}
		}
	case 150:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1186
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.typ = yylex.(*lexer).pushType(&Type{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Kind: Enum, Tag: yyDollar[2].str})
		}
	case 151:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cc.y:1191
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[6].span)
			t := &Type{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Kind: Enum, Tag: yyDollar[2].str, Decls: yyDollar[4].decls}
			for _, d := range yyDollar[4].decls {
				d.Type = t
			}
			yyVAL.typ = yylex.(*lexer).pushType(t)
		}
	case 152:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1202
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			var x *Init
			if yyDollar[2].expr != nil {
				x = &Init{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Expr: yyDollar[2].expr}
			}
			yyVAL.decl = &Decl{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Name: yyDollar[1].str, Init: x}
			yylex.(*lexer).pushDecl(yyVAL.decl)
		}
	case 153:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1214
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.expr = yyDollar[2].expr
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1222
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.init = &Init{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Expr: yyDollar[1].expr}
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1227
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.init = &Init{SyntaxInfo: SyntaxInfo{Span: yyVAL.span}, Braced: yyDollar[1].inits}
		}
	case 156:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1234
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.inits = []*Init{}
		}
	case 157:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cc.y:1239
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[4].span)
			yyVAL.inits = append(yyDollar[2].inits, yyDollar[3].init)
		}
	case 158:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cc.y:1244
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[5].span)
			yyVAL.inits = append(yyDollar[2].inits, yyDollar[3].init)
		}
	case 159:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1250
		{
			yyVAL.span = Span{}
			yyVAL.inits = nil
		}
	case 160:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1255
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.inits = append(yyDollar[1].inits, yyDollar[2].init)
		}
	case 161:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1262
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.init = yyDollar[1].init
		}
	case 162:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1267
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.init = yyDollar[3].init
			yyVAL.init.Prefix = yyDollar[1].prefixes
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1275
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.prefix = &Prefix{Span: yyVAL.span, Index: yyDollar[2].expr}
		}
	case 164:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1281
		{
			yyVAL.span = Span{}
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1285
		{
			yyVAL.span = yyDollar[1].span
		}
	case 166:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1290
		{
			yyVAL.span = Span{}
		}
	case 167:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1294
		{
			yyVAL.span = yyDollar[1].span
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1303
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.prefixes = []*Prefix{yyDollar[1].prefix}
		}
	case 169:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1308
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.prefixes = append(yyDollar[1].prefixes, yyDollar[2].prefix)
		}
	case 170:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1314
		{
			yyVAL.span = Span{}
			yyVAL.str = ""
		}
	case 171:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1319
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.str = yyDollar[1].str
		}
	case 172:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1325
		{
			yyVAL.span = Span{}
			yyVAL.expr = nil
		}
	case 173:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1330
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.expr = yyDollar[1].expr
		}
	case 174:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1336
		{
			yyVAL.span = Span{}
			yyVAL.expr = nil
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1341
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.expr = yyDollar[1].expr
		}
	case 176:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1348
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.exprs = []*Expr{yyDollar[1].expr}
		}
	case 177:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1353
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 178:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1359
		{
			yyVAL.span = Span{}
			yyVAL.exprs = nil
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1364
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 180:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1370
		{
			yyVAL.span = Span{}
			yyVAL.decls = nil
		}
	case 181:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1375
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.decls = append(yyDollar[1].decls, yyDollar[2].decls...)
		}
	case 182:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1381
		{
			yyVAL.span = Span{}
			yyVAL.labels = nil
		}
	case 183:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1386
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.labels = append(yyDollar[1].labels, yyDollar[2].label)
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1393
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decls = []*Decl{yyDollar[1].decl}
		}
	case 185:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1398
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.decls = append(yyDollar[1].decls, yyDollar[3].decl)
		}
	case 186:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1404
		{
			yyVAL.span = Span{}
			yyVAL.decls = nil
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1409
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decls = yyDollar[1].decls
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1416
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.idecs = []idecor{yyDollar[1].idec}
		}
	case 189:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1421
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.idecs = append(yyDollar[1].idecs, yyDollar[3].idec)
		}
	case 190:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1427
		{
			yyVAL.span = Span{}
			yyVAL.idecs = nil
		}
	case 191:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1432
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.idecs = yyDollar[1].idecs
		}
	case 192:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1439
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 193:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1444
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[2].str)
		}
	case 194:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1450
		{
			yyVAL.span = Span{}
			yyVAL.strs = nil
		}
	case 195:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1455
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.strs = yyDollar[1].strs
		}
	case 196:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1462
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 197:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1467
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[2].str)
		}
	case 198:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1473
		{
			yyVAL.span = Span{}
			yyVAL.strs = nil
		}
	case 199:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1478
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.strs = yyDollar[1].strs
		}
	case 200:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1485
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 201:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1490
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[2].str)
		}
	case 202:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1496
		{
			yyVAL.span = Span{}
			yyVAL.strs = nil
		}
	case 203:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1501
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.strs = yyDollar[1].strs
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1508
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decors = nil
			yyVAL.decors = append(yyVAL.decors, yyDollar[1].decor)
		}
	case 205:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1514
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.decors = append(yyDollar[1].decors, yyDollar[3].decor)
		}
	case 206:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1520
		{
			yyVAL.span = Span{}
			yyVAL.decors = nil
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1525
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decors = yyDollar[1].decors
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1532
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decls = yyDollar[1].decls
		}
	case 209:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1537
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.decls = append(yyDollar[1].decls, yyDollar[2].decls...)
		}
	case 210:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cc.y:1543
		{
			yyVAL.span = Span{}
			yyVAL.expr = nil
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1548
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.expr = yyDollar[1].expr
		}
	case 212:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1555
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.decls = []*Decl{yyDollar[1].decl}
		}
	case 213:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cc.y:1560
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[3].span)
			yyVAL.decls = append(yyDollar[1].decls, yyDollar[3].decl)
		}
	case 214:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cc.y:1567
		{
			yyVAL.span = yyDollar[1].span
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 215:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cc.y:1572
		{
			yyVAL.span = span(yyDollar[1].span, yyDollar[2].span)
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[2].str)
		}
	}
	goto yystack /* stack new state and value */
}
